#!/usr/bin/env python3
"""Scheduler-control command handlers extracted from management handlers."""

from typing import Any, Callable, Dict, List, Optional

from aoe_tg_scheduler_auto import _handle_auto_command
from aoe_tg_scheduler_capacity import _provider_capacity_memory_lines
from aoe_tg_scheduler_focus_panic import _handle_focus_command, _handle_panic_command
from aoe_tg_scheduler_offdesk import _handle_offdesk_command

def handle_scheduler_control_command(
    *,
    cmd: str,
    args: Any,
    manager_state: Dict[str, Any],
    chat_id: str,
    chat_role: str,
    rest: str,
    send: Callable[..., bool],
    get_default_mode: Callable[[Dict[str, Any], str], str],
    get_pending_mode: Callable[[Dict[str, Any], str], str],
    get_chat_report_level: Callable[[Dict[str, Any], str, str], str],
    get_chat_room: Callable[[Dict[str, Any], str, str], str],
    set_default_mode: Callable[[Dict[str, Any], str, str], None],
    set_chat_report_level: Callable[[Dict[str, Any], str, str], None],
    set_chat_room: Callable[[Dict[str, Any], str, str], None],
    clear_default_mode: Callable[[Dict[str, Any], str], bool],
    clear_pending_mode: Callable[[Dict[str, Any], str], bool],
    clear_confirm_action: Callable[[Dict[str, Any], str], bool],
    clear_chat_report_level: Callable[[Dict[str, Any], str], bool],
    save_manager_state: Callable[..., None],
    resolve_project_entry: Callable[[Dict[str, Any], str], tuple[str, Dict[str, Any]]],
    project_lock_row: Callable[[Dict[str, Any]], Dict[str, Any]],
    project_lock_label: Callable[[Dict[str, Any]], str],
    parse_replace_sync_flag: Callable[[List[str]], bool | None],
    normalize_prefetch_token: Callable[[Any], str],
    prefetch_display: Callable[[Any, Any, bool], str],
    compact_reason: Callable[[Any, int], str],
    status_report_level: Callable[[List[str], str], str],
    focused_project_snapshot_lines: Callable[[Dict[str, Any]], List[str]],
    ops_scope_summary: Callable[[Dict[str, Any]], Dict[str, List[str]]],
    ops_scope_compact_lines: Callable[[Dict[str, Any], int, str], List[str]],
    offdesk_prepare_targets: Callable[[Dict[str, Any], str], List[tuple[str, Dict[str, Any]]]],
    offdesk_prepare_project_report: Callable[[Dict[str, Any], str, Dict[str, Any]], Dict[str, Any]],
    sort_offdesk_reports: Callable[[List[Dict[str, Any]]], List[Dict[str, Any]]],
    offdesk_review_reply_markup: Callable[[List[Dict[str, Any]], bool], Dict[str, Any]],
    offdesk_prepare_reply_markup: Callable[[List[Dict[str, Any]], int, bool], Dict[str, Any]],
    auto_state_path: Callable[[Any], Any],
    offdesk_state_path: Callable[[Any], Any],
    provider_capacity_state_path: Callable[[Any], Any],
    load_auto_state: Callable[[Any], Dict[str, Any]],
    save_auto_state: Callable[[Any, Dict[str, Any]], None],
    load_offdesk_state: Callable[[Any], Dict[str, Any]],
    save_offdesk_state: Callable[[Any, Dict[str, Any]], None],
    load_provider_capacity_state: Callable[[Any], Dict[str, Any]],
    save_provider_capacity_state: Callable[[Any, Dict[str, Any]], None],
    scheduler_session_name: Callable[[], str],
    tmux_has_session: Callable[[str], bool],
    tmux_auto_command: Callable[[Any, str], tuple[bool, str]],
    now_iso: Callable[[], str],
    default_auto_interval_sec: int,
    default_auto_idle_sec: int,
    default_auto_max_failures: int,
    default_offdesk_command: str,
    default_offdesk_prefetch: str,
    default_offdesk_prefetch_since: str,
    default_offdesk_report_level: str,
    default_offdesk_room: str,
    record_outcome: Optional[Callable[[Dict[str, Any]], None]] = None,
) -> bool:
    if cmd == "focus":
        return _handle_focus_command(
            args=args,
            manager_state=manager_state,
            chat_id=chat_id,
            chat_role=chat_role,
            rest=rest,
            send=send,
            save_manager_state=save_manager_state,
            resolve_project_entry=resolve_project_entry,
            project_lock_row=project_lock_row,
            project_lock_label=project_lock_label,
            now_iso=now_iso,
        )
    if cmd == "panic":
        return _handle_panic_command(
            args=args,
            manager_state=manager_state,
            chat_id=chat_id,
            chat_role=chat_role,
            rest=rest,
            send=send,
            get_default_mode=get_default_mode,
            get_pending_mode=get_pending_mode,
            clear_default_mode=clear_default_mode,
            clear_pending_mode=clear_pending_mode,
            clear_confirm_action=clear_confirm_action,
            save_manager_state=save_manager_state,
            auto_state_path=auto_state_path,
            offdesk_state_path=offdesk_state_path,
            load_auto_state=load_auto_state,
            save_auto_state=save_auto_state,
            load_offdesk_state=load_offdesk_state,
            save_offdesk_state=save_offdesk_state,
            scheduler_session_name=scheduler_session_name,
            tmux_has_session=tmux_has_session,
            tmux_auto_command=tmux_auto_command,
            now_iso=now_iso,
        )
    if cmd == "offdesk":
        return _handle_offdesk_command(
            args=args,
            manager_state=manager_state,
            chat_id=chat_id,
            chat_role=chat_role,
            rest=rest,
            send=send,
            get_default_mode=get_default_mode,
            get_pending_mode=get_pending_mode,
            get_chat_report_level=get_chat_report_level,
            get_chat_room=get_chat_room,
            set_default_mode=set_default_mode,
            set_chat_report_level=set_chat_report_level,
            set_chat_room=set_chat_room,
            clear_default_mode=clear_default_mode,
            clear_pending_mode=clear_pending_mode,
            clear_confirm_action=clear_confirm_action,
            clear_chat_report_level=clear_chat_report_level,
            save_manager_state=save_manager_state,
            parse_replace_sync_flag=parse_replace_sync_flag,
            status_report_level=status_report_level,
            prefetch_display=prefetch_display,
            focused_project_snapshot_lines=focused_project_snapshot_lines,
            ops_scope_summary=ops_scope_summary,
            ops_scope_compact_lines=ops_scope_compact_lines,
            project_lock_row=project_lock_row,
            project_lock_label=project_lock_label,
            offdesk_prepare_targets=offdesk_prepare_targets,
            offdesk_prepare_project_report=offdesk_prepare_project_report,
            sort_offdesk_reports=sort_offdesk_reports,
            offdesk_review_reply_markup=offdesk_review_reply_markup,
            offdesk_prepare_reply_markup=offdesk_prepare_reply_markup,
            auto_state_path=auto_state_path,
            offdesk_state_path=offdesk_state_path,
            provider_capacity_state_path=provider_capacity_state_path,
            load_auto_state=load_auto_state,
            save_auto_state=save_auto_state,
            load_offdesk_state=load_offdesk_state,
            save_offdesk_state=save_offdesk_state,
            load_provider_capacity_state=load_provider_capacity_state,
            save_provider_capacity_state=save_provider_capacity_state,
            tmux_auto_command=tmux_auto_command,
            now_iso=now_iso,
            default_offdesk_command=default_offdesk_command,
            default_offdesk_prefetch=default_offdesk_prefetch,
            default_offdesk_prefetch_since=default_offdesk_prefetch_since,
            default_offdesk_report_level=default_offdesk_report_level,
            default_offdesk_room=default_offdesk_room,
            default_auto_interval_sec=default_auto_interval_sec,
            default_auto_idle_sec=default_auto_idle_sec,
        )
    if cmd == "auto":
        return _handle_auto_command(
            args=args,
            manager_state=manager_state,
            chat_id=chat_id,
            chat_role=chat_role,
            rest=rest,
            send=send,
            get_chat_report_level=get_chat_report_level,
            status_report_level=status_report_level,
            parse_replace_sync_flag=parse_replace_sync_flag,
            normalize_prefetch_token=normalize_prefetch_token,
            prefetch_display=prefetch_display,
            compact_reason=compact_reason,
            focused_project_snapshot_lines=focused_project_snapshot_lines,
            ops_scope_compact_lines=ops_scope_compact_lines,
            project_lock_row=project_lock_row,
            project_lock_label=project_lock_label,
            auto_state_path=auto_state_path,
            load_auto_state=load_auto_state,
            save_auto_state=save_auto_state,
            provider_capacity_state_path=provider_capacity_state_path,
            load_provider_capacity_state=load_provider_capacity_state,
            save_provider_capacity_state=save_provider_capacity_state,
            scheduler_session_name=scheduler_session_name,
            tmux_has_session=tmux_has_session,
            tmux_auto_command=tmux_auto_command,
            now_iso=now_iso,
            default_auto_interval_sec=default_auto_interval_sec,
            default_auto_idle_sec=default_auto_idle_sec,
            default_auto_max_failures=default_auto_max_failures,
            record_outcome=record_outcome,
        )
    return False
